import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  FileText,
  Shield,
  Users,
  Gavel,
  RefreshCw,
  AlertTriangle,
  CheckCircle,
  Globe,
  Phone,
  Mail,
  MapPin,
  ArrowLeft,
  Calendar,
  Zap,
  Lock,
  CreditCard,
  UserCheck,
  Scale
} from 'lucide-react';

export default function TermsConditionsPage() {
  const sections = [
    {
      id: 'electronic-record',
      title: 'Electronic Record',
      icon: <FileText className="w-6 h-6" />,
      content: `This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.`
    },
    {
      id: 'publication',
      title: 'Publication Guidelines',
      icon: <Globe className="w-6 h-6" />,
      content: `This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.elitecrows.in/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').`
    },
    {
      id: 'platform-owner',
      title: 'Platform Ownership',
      icon: <Users className="w-6 h-6" />,
      content: `The Platform is owned by PUGALENTHI G, a company incorporated under the Companies Act, 1956 with its registered office at ERODE, TAMILNADU, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').`
    }
  ];

  const termsOfUse = [
    {
      title: 'User Agreement',
      icon: <UserCheck className="w-5 h-5" />,
      content: 'Your use of the Platform and services are governed by these Terms of Use. By using the Platform, you are contracting with the Platform Owner and these terms constitute your binding obligations.'
    },
    {
      title: 'Account Information',
      icon: <Shield className="w-5 h-5" />,
      content: 'To access and use the Services, you agree to provide true, accurate and complete information during and after registration, and you shall be responsible for all acts done through your registered account.'
    },
    {
      title: 'No Warranty',
      icon: <AlertTriangle className="w-5 h-5" />,
      content: 'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website.'
    },
    {
      title: 'User Risk',
      icon: <Scale className="w-5 h-5" />,
      content: 'Your use of our Services and the Platform is solely at your own risk and discretion. You are required to independently assess that the Services meet your requirements.'
    },
    {
      title: 'Intellectual Property',
      icon: <Lock className="w-5 h-5" />,
      content: 'The contents of the Platform are proprietary to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.'
    },
    {
      title: 'Payment Terms',
      icon: <CreditCard className="w-5 h-5" />,
      content: 'You agree to pay us the charges associated with availing the Services as per the agreed terms and conditions.'
    }
  ];

  const legalTerms = [
    {
      title: 'Lawful Use',
      description: 'You agree not to use the Platform for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.'
    },
    {
      title: 'Third Party Links',
      description: 'You acknowledge that the website may contain links to other third party websites. On accessing these links, you will be governed by their respective terms of use and privacy policies.'
    },
    {
      title: 'Legal Contract',
      description: 'You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract.'
    },
    {
      title: 'Indemnification',
      description: 'You shall indemnify and hold harmless Platform Owner from any claim, demand, or actions including reasonable attorney\'s fees, made by any third party due to your breach of these Terms.'
    },
    {
      title: 'Force Majeure',
      description: 'The parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.'
    },
    {
      title: 'Governing Law',
      description: 'These Terms shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of courts in Tamil Nadu.'
    }
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-black/90 backdrop-blur-sm border-b border-gray-800">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="sm" className="text-gray-400 hover:text-white">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold">EliteCrows Infotech</span>
              </div>
            </div>
            <Badge variant="outline" className="bg-blue-900/50 border-blue-600 text-blue-300">
              Legal Document
            </Badge>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-12 md:py-20 px-4 bg-gradient-to-br from-blue-900/20 to-purple-900/20">
        <div className="container mx-auto text-center">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center justify-center mb-6">
              <div className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center">
                <Gavel className="w-8 h-8 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 bg-gradient-to-r from-white to-blue-200 bg-clip-text text-transparent">
              Terms & Conditions
            </h1>
            <p className="text-lg md:text-xl text-gray-300 mb-8 leading-relaxed">
              Please read these terms and conditions carefully before using our platform and services.
            </p>
            <div className="flex items-center justify-center space-x-4 text-sm text-gray-400">
              <div className="flex items-center space-x-2">
                <Calendar className="w-4 h-4" />
                <span>Last updated: January 2025</span>
              </div>
              <div className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                <span>Legally Binding</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Sections */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="grid gap-8">
            {sections.map((section, index) => (
              <Card key={section.id} className="bg-gray-900/50 border-gray-700">
                <CardContent className="p-6 md:p-8">
                  <div className="flex items-start space-x-4">
                    <div className="text-blue-400 mt-1">{section.icon}</div>
                    <div className="flex-1">
                      <h2 className="text-xl md:text-2xl font-semibold mb-4">{section.title}</h2>
                      <p className="text-gray-300 leading-relaxed">{section.content}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Terms of Use */}
      <section className="py-12 md:py-20 px-4 bg-gray-950">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Terms of Use</h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              The following terms govern your use of our platform and services
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {termsOfUse.map((term, index) => (
              <Card key={index} className="bg-gray-900/50 border-gray-700 hover:border-blue-600 transition-all duration-300">
                <CardContent className="p-6">
                  <div className="flex items-start space-x-3 mb-4">
                    <div className="text-blue-400">{term.icon}</div>
                    <h3 className="font-semibold">{term.title}</h3>
                  </div>
                  <p className="text-gray-300 text-sm leading-relaxed">{term.content}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Legal Terms */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Legal Terms</h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              Important legal provisions and your obligations as a user
            </p>
          </div>

          <div className="space-y-6">
            {legalTerms.map((term, index) => (
              <Card key={index} className="bg-gray-900/50 border-gray-700">
                <CardContent className="p-6">
                  <div className="flex items-start space-x-4">
                    <div className="w-8 h-8 bg-blue-600/20 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                      <span className="text-blue-400 font-semibold text-sm">{index + 1}</span>
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold mb-2">{term.title}</h3>
                      <p className="text-gray-300 leading-relaxed">{term.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Privacy & Consent */}
      <section className="py-12 md:py-20 px-4 bg-gray-950">
        <div className="container mx-auto max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-8">
            <Card className="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-600/30">
              <CardContent className="p-6 md:p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <Shield className="w-6 h-6 text-blue-400" />
                  <h3 className="text-xl font-semibold">Privacy & Consent</h3>
                </div>
                <div className="space-y-4 text-gray-300">
                  <p className="leading-relaxed">
                    By visiting our Platform or providing your information, you consent to the collection, use, storage, 
                    disclosure and processing of your information in accordance with our Privacy Policy.
                  </p>
                  <p className="leading-relaxed">
                    You consent to us contacting you through SMS, instant messaging apps, call and/or e-mail for the 
                    purposes specified in our Privacy Policy.
                  </p>
                  <p className="leading-relaxed">
                    You have the option to withdraw your consent by writing to our Grievance Officer. However, 
                    withdrawal of consent may restrict or deny the provision of our services.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-gray-900/50 border-gray-700">
              <CardContent className="p-6 md:p-8">
                <div className="flex items-center space-x-3 mb-6">
                  <RefreshCw className="w-6 h-6 text-green-400" />
                  <h3 className="text-xl font-semibold">Refund Policy</h3>
                </div>
                <div className="space-y-4">
                  <div className="bg-red-900/20 border border-red-600/30 rounded-lg p-4">
                    <div className="flex items-center space-x-2 mb-2">
                      <AlertTriangle className="w-5 h-5 text-red-400" />
                      <span className="font-semibold text-red-300">Important Notice</span>
                    </div>
                    <p className="text-gray-300 text-sm">
                      We are not providing any kind of refund for our services. All sales are final.
                    </p>
                  </div>
                  <p className="text-gray-400 text-sm leading-relaxed">
                    Please carefully review all service descriptions, terms, and conditions before making any purchase. 
                    By proceeding with the transaction, you acknowledge and accept this no-refund policy.
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Contact Information */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-4xl">
          <Card className="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-600/30">
            <CardContent className="p-6 md:p-8 text-center">
              <h3 className="text-2xl font-bold mb-6">Questions About These Terms?</h3>
              <p className="text-gray-300 mb-8 max-w-2xl mx-auto">
                All concerns or communications relating to these Terms must be communicated to us using the contact information below.
              </p>
              
              <div className="grid md:grid-cols-3 gap-6 mb-8">
                <div className="flex flex-col items-center space-y-2">
                  <Mail className="w-8 h-8 text-blue-400" />
                  <span className="font-semibold">Email</span>
                  <span className="text-gray-300 text-sm">elitecrowsindia@gmail.com</span>
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Phone className="w-8 h-8 text-green-400" />
                  <span className="font-semibold">Phone</span>
                  <span className="text-gray-300 text-sm">+91 63831 06107</span>
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <MapPin className="w-8 h-8 text-purple-400" />
                  <span className="font-semibold">Address</span>
                  <span className="text-gray-300 text-sm">Erode, Tamil Nadu, India</span>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button className="bg-blue-600 hover:bg-blue-700">
                  <Mail className="mr-2 w-4 h-4" />
                  Contact Us
                </Button>
                <Button variant="outline" className="border-gray-600 text-white hover:bg-gray-800">
                  <FileText className="mr-2 w-4 h-4" />
                  Download PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 md:py-12 px-4 bg-gray-950 border-t border-gray-800">
        <div className="container mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold">EliteCrows Infotech</span>
          </div>
          <p className="text-gray-400 text-sm mb-4">
            © 2025 EliteCrows Infotech. All rights reserved.
          </p>
          <div className="flex items-center justify-center space-x-4 text-xs text-gray-500">
            <span>Terms & Conditions</span>
            <span>•</span>
            <span>Privacy Policy</span>
            <span>•</span>
            <span>Refund Policy</span>
          </div>
        </div>
      </footer>
    </div>
  );
}