import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  FileText,
  Shield,
  Users,
  Gavel,
  RefreshCw,
  AlertTriangle,
  CheckCircle,
  Globe,
  Phone,
  Mail,
  MapPin,
  ArrowLeft,
  Calendar,
  Zap,
  Lock,
  CreditCard,
  UserCheck,
  Scale,
  ShieldAlert
} from 'lucide-react';

export default function TermsConditionsPage() {
  const sections = [
    {
      id: 'electronic-record',
      title: 'Electronic Record',
      icon: <FileText className="w-6 h-6" />,
      content: `This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.`
    },
    {
      id: 'publication',
      title: 'Publication Guidelines',
      icon: <Globe className="w-6 h-6" />,
      content: `This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://www.elitecrows.in/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').`
    },
    {
      id: 'platform-owner',
      title: 'Platform Ownership',
      icon: <Users className="w-6 h-6" />,
      content: `The Platform is owned by PUGALENTHI G, a company incorporated under the Companies Act, 1956 with its registered office at ERODE, TAMILNADU, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').`
    }
  ];

  const termsOfUse = [
    {
      title: 'User Agreement',
      icon: <UserCheck className="w-5 h-5" />,
      content: 'Your use of the Platform and services are governed by these Terms of Use. By using the Platform, you are contracting with the Platform Owner and these terms constitute your binding obligations.'
    },
    {
      title: 'Account Information',
      icon: <Shield className="w-5 h-5" />,
      content: 'To access and use the Services, you agree to provide true, accurate and complete information during and after registration, and you shall be responsible for all acts done through your registered account.'
    },
    {
      title: 'No Warranty',
      icon: <AlertTriangle className="w-5 h-5" />,
      content: 'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website.'
    },
    {
      title: 'User Risk',
      icon: <Scale className="w-5 h-5" />,
      content: 'Your use of our Services and the Platform is solely at your own risk and discretion. You are required to independently assess that the Services meet your requirements.'
    },
    {
      title: 'Intellectual Property',
      icon: <Lock className="w-5 h-5" />,
      content: 'The contents of the Platform are proprietary to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents.'
    },
    {
      title: 'Payment Terms',
      icon: <CreditCard className="w-5 h-5" />,
      content: 'You agree to pay us the charges associated with availing the Services as per the agreed terms and conditions.'
    }
  ];

  const legalTerms = [
    {
      title: 'Lawful Use',
      description: 'You agree not to use the Platform for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.'
    },
    {
      title: 'Third Party Links',
      description: 'You acknowledge that the website may contain links to other third party websites. On accessing these links, you will be governed by their respective terms of use and privacy policies.'
    },
    {
      title: 'Legal Contract',
      description: 'You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract.'
    },
    {
      title: 'Indemnification',
      description: 'You shall indemnify and hold harmless Platform Owner from any claim, demand, or actions including reasonable attorney\'s fees, made by any third party due to your breach of these Terms.'
    },
    {
      title: 'Force Majeure',
      description: 'The parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.'
    },
    {
      title: 'Governing Law',
      description: 'These Terms shall be governed by and construed in accordance with the laws of India. All disputes shall be subject to the exclusive jurisdiction of courts in Tamil Nadu.'
    }
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-black/90 backdrop-blur-sm border-b border-gray-800">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Button variant="ghost" size="sm" className="text-gray-400 hover:text-white">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
              <div className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <span className="text-xl font-bold">EliteCrows Infotech</span>
              </div>
            </div>
            <Badge variant="outline" className="bg-blue-900/50 border-blue-600 text-blue-300">
              Legal Document
            </Badge>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-12 md:py-20 px-4 bg-gradient-to-br from-blue-900/20 to-purple-900/20">
        <div className="container mx-auto text-center">
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center justify-center mb-6">
              <div className="w-16 h-16 bg-blue-600 rounded-full flex items-center justify-center">
                <Gavel className="w-8 h-8 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 bg-gradient-to-r from-white to-blue-200 bg-clip-text text-transparent">
              Terms & Conditions
            </h1>
            <p className="text-lg md:text-xl text-gray-300 mb-8 leading-relaxed">
              Please read these terms and conditions carefully before using our platform and services.
            </p>
            <div className="flex items-center justify-center space-x-4 text-sm text-gray-400">
              <div className="flex items-center space-x-2">
                <Calendar className="w-4 h-4" />
                <span>Last updated: January 2025</span>
              </div>
              <div className="flex items-center space-x-2">
                <CheckCircle className="w-4 h-4 text-green-500" />
                <span>Legally Binding</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Sections */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="grid gap-8">
            {sections.map((section, index) => (
              <Card key={section.id} className="bg-gray-900/50 border-gray-700">
                <CardContent className="p-6 md:p-8">
                  <div className="flex items-start space-x-4">
                    <div className="text-blue-400 mt-1">{section.icon}</div>
                    <div className="flex-1">
                      <h2 className="text-xl md:text-2xl font-semibold mb-4">{section.title}</h2>
                      <p className="text-gray-300 leading-relaxed">{section.content}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Terms of Use */}
      <section className="py-12 md:py-20 px-4 bg-gray-950">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Terms of Use</h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              The following terms govern your use of our platform and services
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {termsOfUse.map((term, index) => (
              <Card key={index} className="bg-gray-900/50 border-gray-700 hover:border-blue-600 transition-all duration-300">
                <CardContent className="p-6">
                  <div className="flex items-start space-x-3 mb-4">
                    <div className="text-blue-400">{term.icon}</div>
                    <h3 className="font-semibold">{term.title}</h3>
                  </div>
                  <p className="text-gray-300 text-sm leading-relaxed">{term.content}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Legal Terms */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">Legal Terms</h2>
            <p className="text-lg text-gray-400 max-w-3xl mx-auto">
              Important legal provisions and your obligations as a user
            </p>
          </div>

          <div className="space-y-6">
            {legalTerms.map((term, index) => (
              <Card key={index} className="bg-gray-900/50 border-gray-700">
                <CardContent className="p-6">
                  <div className="flex items-start space-x-4">
                    <div className="w-8 h-8 bg-blue-600/20 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                      <span className="text-blue-400 font-semibold text-sm">{index + 1}</span>
                    </div>
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold mb-2">{term.title}</h3>
                      <p className="text-gray-300 leading-relaxed">{term.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Privacy & Consent */}
{/* Privacy Policy */}
  <section className="py-12 md:py-20 px-4 bg-gray-950">
    <div className="container mx-auto max-w-6xl">
      <div className="text-center mb-12">
        <div className="flex items-center justify-center mb-6">
          <div className="w-16 h-16 bg-green-600 rounded-full flex items-center justify-center">
            <Shield className="w-8 h-8 text-white" />
          </div>
        </div>
        <h2 className="text-3xl md:text-4xl font-bold mb-4">Privacy Policy</h2>
        <p className="text-lg text-gray-400 max-w-3xl mx-auto">
          How we collect, use, and protect your personal information
        </p>
      </div>

      <div className="space-y-8">
        {/* Introduction */}
        <Card className="bg-gradient-to-br from-green-900/20 to-blue-900/20 border-green-600/30">
          <CardContent className="p-6 md:p-8">
            <div className="flex items-center space-x-3 mb-6">
              <FileText className="w-6 h-6 text-green-400" />
              <h3 className="text-xl font-semibold">Introduction</h3>
            </div>
            <div className="text-gray-300 leading-relaxed space-y-4">
              <p>
                This Privacy Policy describes how PUGALENTHI G and its affiliates (collectively PUGALENTHI G, we, our, us) collect, use, share, protect or otherwise process your information/personal data through our website https://www.elitecrows.in/ (hereinafter referred to as Platform).
              </p>
              <p>
                We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Collection */}
        <Card className="bg-gray-900/50 border-gray-700">
          <CardContent className="p-6 md:p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Users className="w-6 h-6 text-blue-400" />
              <h3 className="text-xl font-semibold">Data Collection</h3>
            </div>
            <div className="text-gray-300 leading-relaxed space-y-4">
              <p>
                We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship. Some of the information that we may collect includes but is not limited to:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Personal information provided during sign-up such as name, date of birth, address, telephone/mobile number, email ID</li>
                <li>Payment instrument information such as bank account or credit/debit card details</li>
                <li>Biometric information such as facial features (when opted for certain features)</li>
                <li>Transaction information and behavior patterns on our Platform</li>
              </ul>
              <div className="bg-yellow-900/20 border border-yellow-600/30 rounded-lg p-4 mt-4">
                <div className="flex items-center space-x-2 mb-2">
                  <AlertTriangle className="w-5 h-5 text-yellow-400" />
                  <span className="font-semibold text-yellow-300">Important Security Notice</span>
                </div>
                <p className="text-gray-300 text-sm">
                  We will never ask for your debit/credit card PIN, net-banking or mobile banking password via email or phone. If you receive such requests, report them immediately to law enforcement.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Usage */}
        <Card className="bg-gray-900/50 border-gray-700">
          <CardContent className="p-6 md:p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Zap className="w-6 h-6 text-purple-400" />
              <h3 className="text-xl font-semibold">How We Use Your Data</h3>
            </div>
            <div className="text-gray-300 leading-relaxed space-y-4">
              <p>We use personal data to:</p>
              <div className="grid md:grid-cols-2 gap-4">
                <ul className="list-disc list-inside space-y-2">
                  <li>Provide the services you request</li>
                  <li>Enhance customer experience</li>
                  <li>Resolve disputes and troubleshoot problems</li>
                  <li>Inform you about offers and updates</li>
                </ul>
                <ul className="list-disc list-inside space-y-2">
                  <li>Detect and protect against fraud</li>
                  <li>Enforce our terms and conditions</li>
                  <li>Conduct marketing research and analysis</li>
                  <li>Customize your platform experience</li>
                </ul>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Sharing */}
        <Card className="bg-gray-900/50 border-gray-700">
          <CardContent className="p-6 md:p-8">
            <div className="flex items-center space-x-3 mb-6">
              <Globe className="w-6 h-6 text-orange-400" />
              <h3 className="text-xl font-semibold">Data Sharing</h3>
            </div>
            <div className="text-gray-300 leading-relaxed space-y-4">
              <p>We may share your personal data with:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Our group entities, corporate entities, and affiliates</li>
                <li>Third parties such as sellers, business partners, logistics partners</li>
                <li>Payment service providers and reward program partners</li>
                <li>Government agencies or law enforcement when required by law</li>
                <li>Third party rights owners to protect intellectual property</li>
              </ul>
              <p className="text-sm text-gray-400 mt-4">
                These disclosures may be required to provide services, comply with legal obligations, enforce agreements, or prevent fraudulent activities.
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Security & Rights */}
        <div className="grid lg:grid-cols-2 gap-8">
          <Card className="bg-gray-900/50 border-gray-700">
            <CardContent className="p-6 md:p-8">
              <div className="flex items-center space-x-3 mb-6">
                <Lock className="w-6 h-6 text-red-400" />
                <h3 className="text-xl font-semibold">Security Measures</h3>
              </div>
              <div className="text-gray-300 leading-relaxed space-y-4">
                <p>
                  We adopt reasonable security practices and procedures to protect your personal data from unauthorized access, disclosure, loss or misuse.
                </p>
                <p className="text-sm text-gray-400">
                  However, data transmission over the internet cannot always be guaranteed as completely secure. Users are responsible for protecting their login credentials.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-gray-900/50 border-gray-700">
            <CardContent className="p-6 md:p-8">
              <div className="flex items-center space-x-3 mb-6">
                <UserCheck className="w-6 h-6 text-cyan-400" />
                <h3 className="text-xl font-semibold">Your Rights</h3>
              </div>
              <div className="text-gray-300 leading-relaxed space-y-4">
                <p>
                  You may access, rectify, and update your personal data directly through the functionalities provided on the Platform.
                </p>
                <p>
                  You can delete your account by visiting your profile settings, though this will result in losing all account information.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Data Retention & Consent */}
        <div className="grid lg:grid-cols-2 gap-8">
          <Card className="bg-gray-900/50 border-gray-700">
            <CardContent className="p-6 md:p-8">
              <div className="flex items-center space-x-3 mb-6">
                <RefreshCw className="w-6 h-6 text-green-400" />
                <h3 className="text-xl font-semibold">Data Retention</h3>
              </div>
              <div className="text-gray-300 leading-relaxed space-y-4">
                <p>
                  We retain your personal data for a period no longer than required for the purpose it was collected or as required under applicable law.
                </p>
                <p className="text-sm text-gray-400">
                  We may retain data in anonymized form for analytical and research purposes, or if necessary to prevent fraud or for other legitimate purposes.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-blue-900/20 border-blue-600/30">
            <CardContent className="p-6 md:p-8">
              <div className="flex items-center space-x-3 mb-6">
                <CheckCircle className="w-6 h-6 text-blue-400" />
                <h3 className="text-xl font-semibold">Consent</h3>
              </div>
              <div className="text-gray-300 leading-relaxed space-y-4">
                <p>
                  By visiting our Platform, you consent to the collection, use, storage, and processing of your information in accordance with this Privacy Policy.
                </p>
                <p className="text-sm">
                  You can withdraw consent by writing to our Grievance Officer, though this may restrict our service provision.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Policy Changes */}
        <Card className="bg-gradient-to-br from-purple-900/20 to-blue-900/20 border-purple-600/30">
          <CardContent className="p-6 md:p-8 text-center">
            <div className="flex items-center justify-center mb-6">
              <AlertTriangle className="w-6 h-6 text-purple-400" />
            </div>
            <h3 className="text-xl font-semibold mb-4">Policy Updates</h3>
            <p className="text-gray-300 leading-relaxed max-w-2xl mx-auto">
              Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices and will notify you about significant changes as required under applicable laws.
            </p>
          </CardContent>
        </Card>
        <Card className="bg-gradient-to-br from-red-900/20 to-blue-900/20 border-red-600/30">
  <CardContent className="p-6 md:p-8 text-center">
    <div className="flex items-center justify-center mb-6">
      <ShieldAlert className="w-6 h-6 text-purple-400" />
    </div>
    <h3 className="text-xl font-semibold mb-4">Refund Policy</h3>
    <p className="text-gray-300 leading-relaxed max-w-2xl mx-auto">
      We are not providing any kind of refund. All purchases made through our platform are final and non-refundable, regardless of the circumstances. By completing a transaction, you acknowledge and accept this policy.
      <br /><br />
      We strongly encourage users to carefully review product or service details, eligibility, and compatibility before making any payment. If you have questions or concerns prior to a purchase, please contact our support team for clarification.
      <br /><br />
      Exceptions to this policy may only be made if required under applicable consumer protection laws. In such cases, the decision to issue a refund will be at the sole discretion of EliteCrows Infotech and must meet all legal conditions.
    </p>
  </CardContent>
</Card>
      </div>
    </div>
  </section>

  {/* Contact Information */}
  <section className="py-12 md:py-20 px-4">
    <div className="container mx-auto max-w-4xl">
      <Card className="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-600/30">
        <CardContent className="p-6 md:p-8 text-center">
          <h3 className="text-2xl font-bold mb-6">Questions About These Terms?</h3>
          <p className="text-gray-300 mb-8 max-w-2xl mx-auto">
            All concerns or communications relating to these Terms must be communicated to us using the contact information below.
          </p>
          
          <div className="grid md:grid-cols-3 gap-6 mb-8">
            <div className="flex flex-col items-center space-y-2">
              <Mail className="w-8 h-8 text-blue-400" />
              <span className="font-semibold">Email</span>
              <span className="text-gray-300 text-sm">elitecrowsindia@gmail.com</span>
            </div>
            <div className="flex flex-col items-center space-y-2">
              <Phone className="w-8 h-8 text-green-400" />
              <span className="font-semibold">Phone</span>
              <span className="text-gray-300 text-sm">+91 63831 06107</span>
            </div>
            <div className="flex flex-col items-center space-y-2">
              <MapPin className="w-8 h-8 text-purple-400" />
              <span className="font-semibold">Address</span>
              <span className="text-gray-300 text-sm">Erode, Tamil Nadu, India</span>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button className="bg-blue-600 hover:bg-blue-700">
              <Mail className="mr-2 w-4 h-4" />
              Contact Us
            </Button>
            <Button variant="outline" className="border-gray-600 text-white hover:bg-gray-800">
              <FileText className="mr-2 w-4 h-4" />
              Download PDF
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  </section>
      {/* Contact Information */}
      <section className="py-12 md:py-20 px-4">
        <div className="container mx-auto max-w-4xl">
          <Card className="bg-gradient-to-br from-blue-900/20 to-purple-900/20 border-blue-600/30">
            <CardContent className="p-6 md:p-8 text-center">
              <h3 className="text-2xl font-bold mb-6">Questions About These Terms?</h3>
              <p className="text-gray-300 mb-8 max-w-2xl mx-auto">
                All concerns or communications relating to these Terms must be communicated to us using the contact information below.
              </p>
              
              <div className="grid md:grid-cols-3 gap-6 mb-8">
                <div className="flex flex-col items-center space-y-2">
                  <Mail className="w-8 h-8 text-blue-400" />
                  <span className="font-semibold">Email</span>
                  <span className="text-gray-300 text-sm">elitecrowsindia@gmail.com</span>
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <Phone className="w-8 h-8 text-green-400" />
                  <span className="font-semibold">Phone</span>
                  <span className="text-gray-300 text-sm">+91 63831 06107</span>
                </div>
                <div className="flex flex-col items-center space-y-2">
                  <MapPin className="w-8 h-8 text-purple-400" />
                  <span className="font-semibold">Address</span>
                  <span className="text-gray-300 text-sm">Erode, Tamil Nadu, India</span>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button className="bg-blue-600 hover:bg-blue-700">
                  <Mail className="mr-2 w-4 h-4" />
                  Contact Us
                </Button>
                <Button variant="outline" className="border-gray-600 text-white hover:bg-gray-800">
                  <FileText className="mr-2 w-4 h-4" />
                  Download PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 md:py-12 px-4 bg-gray-950 border-t border-gray-800">
        <div className="container mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold">EliteCrows Infotech</span>
          </div>
          <p className="text-gray-400 text-sm mb-4">
            © 2025 EliteCrows Infotech. All rights reserved.
          </p>
          <div className="flex items-center justify-center space-x-4 text-xs text-gray-500">
            <span>Terms & Conditions</span>
            <span>•</span>
            <span>Privacy Policy</span>
            <span>•</span>
            <span>Refund Policy</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
